kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: koozie
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "0.0.0.0"
      - containerPort: 30443
        hostPort: 30443
        listenAddress: "0.0.0.0"
