repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: nginx-ingress
    namespace: nginx
    chart: ingress-nginx/ingress-nginx
    createNamespace: true
    set:
      - name: controller.kind
        value: DaemonSet
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: 30080
      - name: controller.service.nodePorts.https
        value: 30443
  - name: prometheus-operator
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    createNamespace: true
    disableValidation: true
    set:
      - name: prometheus.prometheusSpec.secrets[0]
        value: topokube-koozie-exporter-webhook-secret
      - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
        value: false
    wait: true
  - name: topokube
    namespace: topokube
    chart: ./charts/koozie-exporter
    values:
      - "./charts/koozie-exporter/values.yaml"
    set:
      - name: prometheus.serviceMonitor.enabled
        value: true
    wait: true
    waitForJobs: true
    createNamespace: true
