repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: incubator
    url: https://charts.helm.sh/incubator
releases:
  - name: namespaces
    chart: incubator/raw
    values:
      - resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: nginx
            spec: {}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: topokube
            spec: {}
  - name: nginx-ingress
    namespace: nginx
    chart: stable/nginx-ingress
    needs:
      - namespaces
    set:
      - name: controller.kind
        value: DaemonSet
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: 30080
      - name: controller.service.nodePorts.https
        value: 30443
  - name: topokube
    namespace: topokube
    chart: ./node-app
    needs:
      - namespaces
    values:
      - "./node-app/values.yaml"
    wait: true