repositories:
  - name: stable
    url: https://charts.helm.sh/stable
releases:
  - name: nginx-ingress
    namespace: nginx
    chart: stable/nginx-ingress
    createNamespace: true
    set:
      - name: controller.kind
        value: DaemonSet
      - name: controller.service.type
        value: NodePort
      - name: controller.service.nodePorts.http
        value: 30080
      - name: controller.service.nodePorts.https
        value: 30443
  - name: topokube
    namespace: topokube
    chart: ./charts/node-app
    values:
      - "./charts/node-app/values.yaml"
    wait: true
    waitForJobs: true
    createNamespace: true