apiVersion: v1
kind: Service
metadata:
  name: {{ include "koozie-exporter.fullname" . }}-ui
  labels:
    {{- include "koozie-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: http-ui
  selector:
    {{- include "koozie-exporter.selectorLabels" . | nindent 4 }}
