apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "koozie-exporter.fullname" . }}-hook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "koozie-exporter.fullname" . }}-cert
  labels:
    {{- include "koozie-exporter.labels" . | nindent 4 }}
webhooks:
- name: topokube.github.io
  rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
  failurePolicy: Ignore
  clientConfig:
    service:
      name: {{ include "koozie-exporter.fullname" . }}
      namespace: topokube
      path: /api/kubernetes-webhook
      port: {{ .Values.service.port }}
  sideEffects: "None"
  admissionReviewVersions: ["v1"]
