kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "node-app.fullname" . }}-role
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch