apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app.fullname" . }}-ui
  labels:
    {{- include "node-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: http-ui
  selector:
    {{- include "node-app.selectorLabels" . | nindent 4 }}
