kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "node-app.fullname" . }}-role-binding
  labels:
        {{- include "node-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-app.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "node-app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}